#!/usr/bin/env bash
# Displays Best School 10 times say hi after 9th

COUNTER=0
while [ $COUNTER -lt 11 ]
do
	if [ $COUNTER = 9 ]
	then
		echo "Hi"
	else
		echo "Best School"
	fi
	(( COUNTER+=1 ))
done
