#!/bin/env bash
# Displays Bad luck on 4th, Good luck on 8th
Best School on the rest

COUNTER=1
while [ $COUNTER -lt 11 ]
do
    if [ $COUNTER = 4 ]
    then
        echo "bad luck"
    elif [ $COUNTER = 8 ]
    then
        echo "good luck"
    else
        echo "Best School"
    fi
    (( COUNTER+=1 ))
done
